### ISSUE TITLE
Adjust frequency

### ISSUE THREAD

**Issue by cyrusdavid** [hnq90/GitHubArchive#1]
Is it possible to adjust the frequency of e-mails? Like 3-day intervals.

**Comment by hnq90** [comment]
@vohof I will create a new mailing list which is sent every 3 days. But currently, there's only daily newsletter.

**Comment by hnq90** [comment]
@vohof 
You can subscribe here: 
- [Daily Newsletters](http://eepurl.com/bb4EFL)
- [Every 3 days Newsletters](http://eepurl.com/bc5JV9)
- [Weekly Newsletters](http://eepurl.com/bc5Yn9)

**Comment by cyrusdavid** [comment]
Thanks @hnq90 :sparkles: :sparkles:

**Comment by hnq90** [comment]
:+1:
