### ISSUE TITLE
Could we explain what the metics are more precisely?

### ISSUE THREAD

**Issue by tyler17** [hnq90/GitHubArchive#2]
When a project says, for example, +578/1226, what does the +578 represent?  Number of news stars in the last week? month? day?

**Comment by hnq90** [comment]
@tyler17 
About **+578/1226**, **+578** represents the number of new stars of previous day, and the number, nexts to it, is total stars.

**Comment by tyler17** [comment]
Thanks!

**Comment by hnq90** [comment]
@tyler17 If you have any idea for GitHubArchive, please don't hesitate to tell me about it.
Thank you in advance.

**Comment by venturehacker** [comment]
How does the newsletter calculate these daily star increases?  I don't see this in the code anywhere. Thanks!

**Comment by tyler17** [comment]
How are these daily star increase metrics calculated? I don't see it in the code anywhere. Thanks!

**Comment by hnq90** [comment]
@tyler17 
_starringCount_ is the daily star number and _total_count_ is the total star of a repo.

You can see _total_count_ here: 
`repo['total_count'] = repo_info['stargazers_count']` [L123](https://github.com/hnq90/GitHubArchive/blob/master/daily.rb#L123)

And _starringCount_ is gotten from `@data = get_repos_info(run_query query)`
